import type maplibregl from "maplibre-gl";

/**
 * Real per-entity icons generated by truckermudgeon/maps' `generator
 * spritesheet` command — one PNG per `sprite` value. This covers BOTH:
 *   - road route shields, e.g. sprite "at_a1" -> at_a1.png (Austrian A1)
 *   - company/POI logos, e.g. sprite "polar_fish" -> polar_fish.png
 * Both road and poi features carry a matching `sprite` property, so a style
 * layer can just do `icon-image: ["get", "sprite"]` and get the right icon
 * automatically for either. Place the full icon set (everything from your
 * generator's icons/ output EXCEPT the large europe-map*.png reference
 * screenshots, which aren't per-entity icons) at:
 *   client/public/map-icons/sprites/
 *
 * NOTE ON APPROACH: an earlier version of this lazily loaded icons via
 * MapLibre's `styleimagemissing` event. In practice that never fired a
 * single request (confirmed via DevTools Network tab — not even for roads,
 * which don't have a fallback to short-circuit to), so instead of chasing
 * that further, this version proactively scans whichever tiles are already
 * loaded for their real `sprite` values and preloads those directly. Same
 * reliable eager-loading approach that already works for the category
 * icons in poi-icons.ts.
 */

const SPRITE_ICON_BASE = "/map-icons/sprites";

const requested = new Set<string>();

async function loadSpriteIcon(map: maplibregl.Map, id: string) {
  if (!id || requested.has(id) || map.hasImage(id)) return;
  requested.add(id);

  try {
    const { data } = await map.loadImage(`${SPRITE_ICON_BASE}/${id}.png`);
    if (!map.hasImage(id)) {
      map.addImage(id, data);
      map.triggerRepaint(); // re-evaluate icon-image/coalesce now that this id is available
    }
  } catch {
    // No icon generated for this sprite id, or it failed to load. Deliberately
    // NOT registering any fallback image under this id — that would make a
    // `coalesce` treat it as "available" and show a blank icon forever,
    // instead of correctly falling through to the category icon.
  }
}

function scanLoadedSpriteValues(map: maplibregl.Map, sourceId: string, sourceLayer: string) {
  if (!map.getSource(sourceId) || !map.isSourceLoaded(sourceId)) return;

  let features: maplibregl.GeoJSONFeature[];
  try {
    features = map.querySourceFeatures(sourceId, { sourceLayer });
  } catch {
    return; // source/tiles not ready yet
  }

  for (const feature of features) {
    const sprite = feature.properties?.sprite;
    if (typeof sprite === "string" && sprite) {
      loadSpriteIcon(map, sprite);
    }
  }
}

/**
 * Watches the given vector source and preloads every real sprite icon
 * referenced by features in whichever tiles are currently loaded — re-scans
 * on every new tile load and after each pan/zoom settles. Call this once,
 * right after creating the map.
 */
export function registerSpriteIconLoader(
  map: maplibregl.Map,
  sourceId: string = "ets2",
  sourceLayer: string = "ets2",
) {
  const scan = () => scanLoadedSpriteValues(map, sourceId, sourceLayer);

  map.on("sourcedata", (e) => {
    if (e.sourceId === sourceId && e.isSourceLoaded) scan();
  });
  map.on("moveend", scan);
  map.on("load", scan);
}
